apiVersion: v1
kind: Service
metadata:
  name: stats-api
  namespace: stats-api
spec:
  type: LoadBalancer
  selector:
    app: stats-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80